#!/bin/bash
# Classify and test
# 
# $classifyAndTest <training data h5> <test data h5> <base output location> <classifier type> <subSample> <classifierArgs>

trainData=$1
testData=$2
resultBase=$3
classifierType=$4
subSample=$5
classifierArgs=${6:-""}

echo $trainData
echo $testData

classifierFile=$resultBase/"classifier-"$classifierType".h5"
trainPredFile=$resultBase/"trainPredictions-"$classifierType".h5"
testPredFile=$resultBase/"testPredictions-"$classifierType".h5"

echo $resultBase
echo $classifierFile
echo $trainPredFile
echo $testPredFile
echo $subSample

cwd=`pwd`
cd /groups/saalfeld/home/bogovicj/dev/main/dictionary-feature-classification/python/saalfeldlab

echo "training..."
if [ "$classifierArgs" ]; then
    echo $classifierArgs
    python train.py -d $trainData -o $classifierFile -i $classifierType -c $classifierType -b $subSample --kwargs $classifierArgs
else
    python train.py -d $trainData -o $classifierFile -i $classifierType -c $classifierType -b $subSample
fi
echo "prediction on training data..."
python test.py -d $trainData -f $classifierFile -c $classifierType -p $classifierType -P
echo "prediction on test data..."
python test.py -d $testData -f $classifierFile -c $classifierType -p $classifierType -P

cd $cwd
echo "done!"
