#!/bin/bash
# Wrapper around learnDictionary.py for use with run_script
# learnDictSpams <input img h5> <other params...>
# 
# See evalDictionary.py for parameter details.

saalfeldPyDir="/groups/saalfeld/home/bogovicj/dev/main/dictionary-feature-classification/python/saalfeldlab"

outdir=$1
shift

imgPath=$1
shift
dictPath=$1
shift

echo $imgPath
echo $dictPath

# remove dir if img is a path
imgFn=${imgPath##*/}

# backup learn dictionary
#cp $saalfeldPyDir/evalDictionary.py $outdir
#chmod 0444 $outdir/evalDictionary.py

python $saalfeldPyDir/evalDictionary.py -i $imgPath -c $dictPath $@
