#!/bin/bash
# Wrapper around learnDictionary.py for use with run_script
# learnDictSpams <input img h5> <other params...>
# 
# See learnDictionary.py for parameter details.

saalfeldPyDir="/groups/saalfeld/home/bogovicj/dev/main/dictionary-feature-classification/python/saalfeldlab"

outdir=$1
shift

imgPath=$1
shift
testImgPath=$1
shift

# remove dir if img is a path
imgFn=${imgPath##*/}
tmp=`echo $imgFn | sed 's/.h5/_dict.h5/g'`
dictFn="$outdir/$tmp"

echo $dictFn

# backup learn dictionary
cp $saalfeldPyDir/learnDictionary.py $outdir
chmod 0444 $outdir/learnDictionary.py
cp $saalfeldPyDir/evalDictionary.py $outdir
chmod 0444 $outdir/evalDictionary.py

echo " ########################## "
echo " TRAINING "
echo " ########################## "
python $outdir/learnDictionary.py -i $imgPath -o $dictFn $@


echo " ########################## "
echo " TESTING "
echo " ########################## "
python $outdir/evalDictionary.py -i $testImgPath -c $dictFn -n 1000 -r 4 -p "9-9-9" -f 3 -u

echo " all done  "
